deploy:
  - provider: script
    script: echo "test"
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master